name: epubber
description: Flutter widget for view EPUB documents on on Web, MacOs, Android and iOS. Based on epub_view, which was based on dart-epub package.
repository: https://github.com/nequam/epub_view.git
issue_tracker: https://github.com/nequam/epub_view/issues
version: 0.9.8

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  epubx: ^3.0.0
  equatable: ^2.0.3
  html: ^0.15.0
  flutter_html: ^2.1.5
  scrollable_positioned_list: ^0.2.2
  rxdart: ^0.27.2
  collection: ^1.15.0
  flutter_math_fork: ^0.4.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

